/*
 * Copyright 2017 Vinícius Petrocione Jardim
 */

package com.vpjardim.contactsfix;

import java.util.HashMap;

/**
 * @author Vinícius Jardim
 * 2017/02/15
 */
public final class Tables {

    public static final class CRow {
        public String countryCode;
        public String isoCode2;
        public String isoCode3;
        public String countryName;

        public CRow(String countryCode, String isoCode2, String isoCode3, String countryName) {
            this.countryCode = countryCode;
            this.isoCode2 = isoCode2;
            this.isoCode3 = isoCode3;
            this.countryName = countryName;
        }

        @Override
        public String toString() {
            return countryCode + " " + countryName;
        }
    }

    public static final class ARow {
        public String areaCode;
        public String isoCode2;
        public String isoCode3;
        public String countryName;
        public String stateCode;
        public String stateName;

        public ARow(String areaCode, String isoCode2, String isoCode3, String countryName,
                    String stateCode, String stateName) {

            this.areaCode = areaCode;
            this.isoCode2 = isoCode2;
            this.isoCode3 = isoCode3;
            this.countryName = countryName;
            this.stateCode = stateCode;
            this.stateName = stateName;
        }

        @Override
        public String toString() {
            return areaCode + " " + countryName;
        }
    }

    public static final HashMap<String, CRow> countryCodes = new HashMap<>();
    public static final HashMap<String, ARow> areaCodes = new HashMap<>();

    static {
        countryCodes.put("1",       new CRow("1",       "US", "USA", "United States"));
        countryCodes.put("7",       new CRow("7",       "RU", "RUS", "Russia"));
        countryCodes.put("20",      new CRow("20",      "EG", "EGY", "Egypt"));
        countryCodes.put("27",      new CRow("27",      "ZA", "ZAF", "South Africa"));
        countryCodes.put("30",      new CRow("30",      "GR", "GRC", "Greece"));
        countryCodes.put("31",      new CRow("31",      "NL", "NLD", "Netherlands"));
        countryCodes.put("32",      new CRow("32",      "BE", "BEL", "Belgium"));
        countryCodes.put("33",      new CRow("33",      "FR", "FRA", "France"));
        countryCodes.put("34",      new CRow("34",      "ES", "ESP", "Spain"));
        countryCodes.put("36",      new CRow("36",      "HU", "HUN", "Hungary"));
        countryCodes.put("39",      new CRow("39",      "IT", "ITA", "Italy"));
        countryCodes.put("40",      new CRow("40",      "RO", "ROU", "Romania"));
        countryCodes.put("41",      new CRow("41",      "CH", "CHE", "Switzerland"));
        countryCodes.put("43",      new CRow("43",      "AT", "AUT", "Austria"));
        countryCodes.put("44",      new CRow("44",      "GB", "GBR", "United Kingdom"));
        countryCodes.put("45",      new CRow("45",      "DK", "DNK", "Denmark"));
        countryCodes.put("46",      new CRow("46",      "SE", "SWE", "Sweden"));
        countryCodes.put("47",      new CRow("47",      "NO", "NOR", "Norway"));
        countryCodes.put("48",      new CRow("48",      "PL", "POL", "Poland"));
        countryCodes.put("49",      new CRow("49",      "DE", "DEU", "Germany"));
        countryCodes.put("51",      new CRow("51",      "PE", "PER", "Peru"));
        countryCodes.put("52",      new CRow("52",      "MX", "MEX", "Mexico"));
        countryCodes.put("53",      new CRow("53",      "CU", "CUB", "Cuba"));
        countryCodes.put("54",      new CRow("54",      "AR", "ARG", "Argentina"));
        countryCodes.put("55",      new CRow("55",      "BR", "BRA", "Brazil"));
        countryCodes.put("56",      new CRow("56",      "CL", "CHL", "Chile"));
        countryCodes.put("57",      new CRow("57",      "CO", "COL", "Colombia"));
        countryCodes.put("58",      new CRow("58",      "VE", "VEN", "Venezuela"));
        countryCodes.put("60",      new CRow("60",      "MY", "MYS", "Malaysia"));
        countryCodes.put("61",      new CRow("61",      "CC", "CCK", "Cocos Islands"));
        countryCodes.put("62",      new CRow("62",      "ID", "IDN", "Indonesia"));
        countryCodes.put("63",      new CRow("63",      "PH", "PHL", "Philippines"));
        countryCodes.put("64",      new CRow("64",      "NZ", "NZL", "New Zealand"));
        countryCodes.put("65",      new CRow("65",      "SG", "SGP", "Singapore"));
        countryCodes.put("66",      new CRow("66",      "TH", "THA", "Thailand"));
        countryCodes.put("81",      new CRow("81",      "JP", "JPN", "Japan"));
        countryCodes.put("82",      new CRow("82",      "KR", "KOR", "South Korea"));
        countryCodes.put("84",      new CRow("84",      "VN", "VNM", "Vietnam"));
        countryCodes.put("86",      new CRow("86",      "CN", "CHN", "China"));
        countryCodes.put("90",      new CRow("90",      "TR", "TUR", "Turkey"));
        countryCodes.put("91",      new CRow("91",      "IN", "IND", "India"));
        countryCodes.put("92",      new CRow("92",      "PK", "PAK", "Pakistan"));
        countryCodes.put("93",      new CRow("93",      "AF", "AFG", "Afghanistan"));
        countryCodes.put("94",      new CRow("94",      "LK", "LKA", "Sri Lanka"));
        countryCodes.put("95",      new CRow("95",      "MM", "MMR", "Myanmar"));
        countryCodes.put("98",      new CRow("98",      "IR", "IRN", "Iran"));
        countryCodes.put("211",     new CRow("211",     "SS", "SSD", "South Sudan"));
        countryCodes.put("212",     new CRow("212",     "MA", "MAR", "Morocco"));
        countryCodes.put("213",     new CRow("213",     "DZ", "DZA", "Algeria"));
        countryCodes.put("216",     new CRow("216",     "TN", "TUN", "Tunisia"));
        countryCodes.put("218",     new CRow("218",     "LY", "LBY", "Libya"));
        countryCodes.put("220",     new CRow("220",     "GM", "GMB", "Gambia"));
        countryCodes.put("221",     new CRow("221",     "SN", "SEN", "Senegal"));
        countryCodes.put("222",     new CRow("222",     "MR", "MRT", "Mauritania"));
        countryCodes.put("223",     new CRow("223",     "ML", "MLI", "Mali"));
        countryCodes.put("224",     new CRow("224",     "GN", "GIN", "Guinea"));
        countryCodes.put("225",     new CRow("225",     "CI", "CIV", "Ivory Coast"));
        countryCodes.put("226",     new CRow("226",     "BF", "BFA", "Burkina Faso"));
        countryCodes.put("227",     new CRow("227",     "NE", "NER", "Niger"));
        countryCodes.put("228",     new CRow("228",     "TG", "TGO", "Togo"));
        countryCodes.put("229",     new CRow("229",     "BJ", "BEN", "Benin"));
        countryCodes.put("230",     new CRow("230",     "MU", "MUS", "Mauritius"));
        countryCodes.put("231",     new CRow("231",     "LR", "LBR", "Liberia"));
        countryCodes.put("232",     new CRow("232",     "SL", "SLE", "Sierra Leone"));
        countryCodes.put("233",     new CRow("233",     "GH", "GHA", "Ghana"));
        countryCodes.put("234",     new CRow("234",     "NG", "NGA", "Nigeria"));
        countryCodes.put("235",     new CRow("235",     "TD", "TCD", "Chad"));
        countryCodes.put("236",     new CRow("236",     "CF", "CAF", "Central African Republic"));
        countryCodes.put("237",     new CRow("237",     "CM", "CMR", "Cameroon"));
        countryCodes.put("238",     new CRow("238",     "CV", "CPV", "Cape Verde"));
        countryCodes.put("239",     new CRow("239",     "ST", "STP", "Sao Tome and Principe"));
        countryCodes.put("240",     new CRow("240",     "GQ", "GNQ", "Equatorial Guinea"));
        countryCodes.put("241",     new CRow("241",     "GA", "GAB", "Gabon"));
        countryCodes.put("242",     new CRow("242",     "CG", "COG", "Republic of the Congo"));
        countryCodes.put("243",     new CRow("243",     "CD", "COD", "Democratic Republic of the Congo"));
        countryCodes.put("244",     new CRow("244",     "AO", "AGO", "Angola"));
        countryCodes.put("245",     new CRow("245",     "GW", "GNB", "Guinea-Bissau"));
        countryCodes.put("246",     new CRow("246",     "IO", "IOT", "British Indian Ocean Territory"));
        countryCodes.put("248",     new CRow("248",     "SC", "SYC", "Seychelles"));
        countryCodes.put("249",     new CRow("249",     "SD", "SDN", "Sudan"));
        countryCodes.put("250",     new CRow("250",     "RW", "RWA", "Rwanda"));
        countryCodes.put("251",     new CRow("251",     "ET", "ETH", "Ethiopia"));
        countryCodes.put("252",     new CRow("252",     "SO", "SOM", "Somalia"));
        countryCodes.put("253",     new CRow("253",     "DJ", "DJI", "Djibouti"));
        countryCodes.put("254",     new CRow("254",     "KE", "KEN", "Kenya"));
        countryCodes.put("255",     new CRow("255",     "TZ", "TZA", "Tanzania"));
        countryCodes.put("256",     new CRow("256",     "UG", "UGA", "Uganda"));
        countryCodes.put("257",     new CRow("257",     "BI", "BDI", "Burundi"));
        countryCodes.put("258",     new CRow("258",     "MZ", "MOZ", "Mozambique"));
        countryCodes.put("260",     new CRow("260",     "ZM", "ZMB", "Zambia"));
        countryCodes.put("261",     new CRow("261",     "MG", "MDG", "Madagascar"));
        countryCodes.put("262",     new CRow("262",     "RE", "REU", "Reunion"));
        countryCodes.put("262",     new CRow("262",     "YT", "MYT", "Mayotte"));
        countryCodes.put("263",     new CRow("263",     "ZW", "ZWE", "Zimbabwe"));
        countryCodes.put("264",     new CRow("264",     "NA", "NAM", "Namibia"));
        countryCodes.put("265",     new CRow("265",     "MW", "MWI", "Malawi"));
        countryCodes.put("266",     new CRow("266",     "LS", "LSO", "Lesotho"));
        countryCodes.put("267",     new CRow("267",     "BW", "BWA", "Botswana"));
        countryCodes.put("268",     new CRow("268",     "SZ", "SWZ", "Swaziland"));
        countryCodes.put("269",     new CRow("269",     "KM", "COM", "Comoros"));
        countryCodes.put("290",     new CRow("290",     "SH", "SHN", "Saint Helena"));
        countryCodes.put("291",     new CRow("291",     "ER", "ERI", "Eritrea"));
        countryCodes.put("297",     new CRow("297",     "AW", "ABW", "Aruba"));
        countryCodes.put("298",     new CRow("298",     "FO", "FRO", "Faroe Islands"));
        countryCodes.put("299",     new CRow("299",     "GL", "GRL", "Greenland"));
        countryCodes.put("350",     new CRow("350",     "GI", "GIB", "Gibraltar"));
        countryCodes.put("351",     new CRow("351",     "PT", "PRT", "Portugal"));
        countryCodes.put("352",     new CRow("352",     "LU", "LUX", "Luxembourg"));
        countryCodes.put("353",     new CRow("353",     "IE", "IRL", "Ireland"));
        countryCodes.put("354",     new CRow("354",     "IS", "ISL", "Iceland"));
        countryCodes.put("355",     new CRow("355",     "AL", "ALB", "Albania"));
        countryCodes.put("356",     new CRow("356",     "MT", "MLT", "Malta"));
        countryCodes.put("357",     new CRow("357",     "CY", "CYP", "Cyprus"));
        countryCodes.put("358",     new CRow("358",     "FI", "FIN", "Finland"));
        countryCodes.put("359",     new CRow("359",     "BG", "BGR", "Bulgaria"));
        countryCodes.put("370",     new CRow("370",     "LT", "LTU", "Lithuania"));
        countryCodes.put("371",     new CRow("371",     "LV", "LVA", "Latvia"));
        countryCodes.put("372",     new CRow("372",     "EE", "EST", "Estonia"));
        countryCodes.put("373",     new CRow("373",     "MD", "MDA", "Moldova"));
        countryCodes.put("374",     new CRow("374",     "AM", "ARM", "Armenia"));
        countryCodes.put("375",     new CRow("375",     "BY", "BLR", "Belarus"));
        countryCodes.put("376",     new CRow("376",     "AD", "AND", "Andorra"));
        countryCodes.put("377",     new CRow("377",     "MC", "MCO", "Monaco"));
        countryCodes.put("378",     new CRow("378",     "SM", "SMR", "San Marino"));
        countryCodes.put("379",     new CRow("379",     "VA", "VAT", "Vatican"));
        countryCodes.put("380",     new CRow("380",     "UA", "UKR", "Ukraine"));
        countryCodes.put("381",     new CRow("381",     "RS", "SRB", "Serbia"));
        countryCodes.put("382",     new CRow("382",     "ME", "MNE", "Montenegro"));
        countryCodes.put("383",     new CRow("383",     "XK", "XKX", "Kosovo"));
        countryCodes.put("385",     new CRow("385",     "HR", "HRV", "Croatia"));
        countryCodes.put("386",     new CRow("386",     "SI", "SVN", "Slovenia"));
        countryCodes.put("387",     new CRow("387",     "BA", "BIH", "Bosnia and Herzegovina"));
        countryCodes.put("389",     new CRow("389",     "MK", "MKD", "Macedonia"));
        countryCodes.put("420",     new CRow("420",     "CZ", "CZE", "Czech Republic"));
        countryCodes.put("421",     new CRow("421",     "SK", "SVK", "Slovakia"));
        countryCodes.put("423",     new CRow("423",     "LI", "LIE", "Liechtenstein"));
        countryCodes.put("500",     new CRow("500",     "FK", "FLK", "Falkland Islands"));
        countryCodes.put("501",     new CRow("501",     "BZ", "BLZ", "Belize"));
        countryCodes.put("502",     new CRow("502",     "GT", "GTM", "Guatemala"));
        countryCodes.put("503",     new CRow("503",     "SV", "SLV", "El Salvador"));
        countryCodes.put("504",     new CRow("504",     "HN", "HND", "Honduras"));
        countryCodes.put("505",     new CRow("505",     "NI", "NIC", "Nicaragua"));
        countryCodes.put("506",     new CRow("506",     "CR", "CRI", "Costa Rica"));
        countryCodes.put("507",     new CRow("507",     "PA", "PAN", "Panama"));
        countryCodes.put("508",     new CRow("508",     "PM", "SPM", "Saint Pierre and Miquelon"));
        countryCodes.put("509",     new CRow("509",     "HT", "HTI", "Haiti"));
        countryCodes.put("590",     new CRow("590",     "BL", "BLM", "Saint Barthelemy"));
        countryCodes.put("590",     new CRow("590",     "MF", "MAF", "Saint Martin"));
        countryCodes.put("591",     new CRow("591",     "BO", "BOL", "Bolivia"));
        countryCodes.put("592",     new CRow("592",     "GY", "GUY", "Guyana"));
        countryCodes.put("593",     new CRow("593",     "EC", "ECU", "Ecuador"));
        countryCodes.put("595",     new CRow("595",     "PY", "PRY", "Paraguay"));
        countryCodes.put("597",     new CRow("597",     "SR", "SUR", "Suriname"));
        countryCodes.put("598",     new CRow("598",     "UY", "URY", "Uruguay"));
        countryCodes.put("599",     new CRow("599",     "CW", "CUW", "Curacao"));
        countryCodes.put("670",     new CRow("670",     "TL", "TLS", "East Timor"));
        countryCodes.put("672",     new CRow("672",     "AQ", "ATA", "Antarctica"));
        countryCodes.put("673",     new CRow("673",     "BN", "BRN", "Brunei"));
        countryCodes.put("674",     new CRow("674",     "NR", "NRU", "Nauru"));
        countryCodes.put("675",     new CRow("675",     "PG", "PNG", "Papua New Guinea"));
        countryCodes.put("676",     new CRow("676",     "TO", "TON", "Tonga"));
        countryCodes.put("677",     new CRow("677",     "SB", "SLB", "Solomon Islands"));
        countryCodes.put("678",     new CRow("678",     "VU", "VUT", "Vanuatu"));
        countryCodes.put("679",     new CRow("679",     "FJ", "FJI", "Fiji"));
        countryCodes.put("680",     new CRow("680",     "PW", "PLW", "Palau"));
        countryCodes.put("681",     new CRow("681",     "WF", "WLF", "Wallis and Futuna"));
        countryCodes.put("682",     new CRow("682",     "CK", "COK", "Cook Islands"));
        countryCodes.put("683",     new CRow("683",     "NU", "NIU", "Niue"));
        countryCodes.put("685",     new CRow("685",     "WS", "WSM", "Samoa"));
        countryCodes.put("686",     new CRow("686",     "KI", "KIR", "Kiribati"));
        countryCodes.put("687",     new CRow("687",     "NC", "NCL", "New Caledonia"));
        countryCodes.put("688",     new CRow("688",     "TV", "TUV", "Tuvalu"));
        countryCodes.put("689",     new CRow("689",     "PF", "PYF", "French Polynesia"));
        countryCodes.put("690",     new CRow("690",     "TK", "TKL", "Tokelau"));
        countryCodes.put("691",     new CRow("691",     "FM", "FSM", "Micronesia"));
        countryCodes.put("692",     new CRow("692",     "MH", "MHL", "Marshall Islands"));
        countryCodes.put("850",     new CRow("850",     "KP", "PRK", "North Korea"));
        countryCodes.put("852",     new CRow("852",     "HK", "HKG", "Hong Kong"));
        countryCodes.put("853",     new CRow("853",     "MO", "MAC", "Macau"));
        countryCodes.put("855",     new CRow("855",     "KH", "KHM", "Cambodia"));
        countryCodes.put("856",     new CRow("856",     "LA", "LAO", "Laos"));
        countryCodes.put("880",     new CRow("880",     "BD", "BGD", "Bangladesh"));
        countryCodes.put("886",     new CRow("886",     "TW", "TWN", "Taiwan"));
        countryCodes.put("960",     new CRow("960",     "MV", "MDV", "Maldives"));
        countryCodes.put("961",     new CRow("961",     "LB", "LBN", "Lebanon"));
        countryCodes.put("962",     new CRow("962",     "JO", "JOR", "Jordan"));
        countryCodes.put("963",     new CRow("963",     "SY", "SYR", "Syria"));
        countryCodes.put("964",     new CRow("964",     "IQ", "IRQ", "Iraq"));
        countryCodes.put("965",     new CRow("965",     "KW", "KWT", "Kuwait"));
        countryCodes.put("966",     new CRow("966",     "SA", "SAU", "Saudi Arabia"));
        countryCodes.put("967",     new CRow("967",     "YE", "YEM", "Yemen"));
        countryCodes.put("968",     new CRow("968",     "OM", "OMN", "Oman"));
        countryCodes.put("970",     new CRow("970",     "PS", "PSE", "Palestine"));
        countryCodes.put("971",     new CRow("971",     "AE", "ARE", "United Arab Emirates"));
        countryCodes.put("972",     new CRow("972",     "IL", "ISR", "Israel"));
        countryCodes.put("973",     new CRow("973",     "BH", "BHR", "Bahrain"));
        countryCodes.put("974",     new CRow("974",     "QA", "QAT", "Qatar"));
        countryCodes.put("975",     new CRow("975",     "BT", "BTN", "Bhutan"));
        countryCodes.put("976",     new CRow("976",     "MN", "MNG", "Mongolia"));
        countryCodes.put("977",     new CRow("977",     "NP", "NPL", "Nepal"));
        countryCodes.put("992",     new CRow("992",     "TJ", "TJK", "Tajikistan"));
        countryCodes.put("993",     new CRow("993",     "TM", "TKM", "Turkmenistan"));
        countryCodes.put("994",     new CRow("994",     "AZ", "AZE", "Azerbaijan"));
        countryCodes.put("995",     new CRow("995",     "GE", "GEO", "Georgia"));
        countryCodes.put("996",     new CRow("996",     "KG", "KGZ", "Kyrgyzstan"));
        countryCodes.put("998",     new CRow("998",     "UZ", "UZB", "Uzbekistan"));
        countryCodes.put("1-242",   new CRow("1-242",   "BS", "BHS", "Bahamas"));
        countryCodes.put("1-246",   new CRow("1-246",   "BB", "BRB", "Barbados"));
        countryCodes.put("1-264",   new CRow("1-264",   "AI", "AIA", "Anguilla"));
        countryCodes.put("1-268",   new CRow("1-268",   "AG", "ATG", "Antigua and Barbuda"));
        countryCodes.put("1-284",   new CRow("1-284",   "VG", "VGB", "British Virgin Islands"));
        countryCodes.put("1-340",   new CRow("1-340",   "VI", "VIR", "U.S. Virgin Islands"));
        countryCodes.put("1-345",   new CRow("1-345",   "KY", "CYM", "Cayman Islands"));
        countryCodes.put("1-441",   new CRow("1-441",   "BM", "BMU", "Bermuda"));
        countryCodes.put("1-473",   new CRow("1-473",   "GD", "GRD", "Grenada"));
        countryCodes.put("1-649",   new CRow("1-649",   "TC", "TCA", "Turks and Caicos Islands"));
        countryCodes.put("1-664",   new CRow("1-664",   "MS", "MSR", "Montserrat"));
        countryCodes.put("1-670",   new CRow("1-670",   "MP", "MNP", "Northern Mariana Islands"));
        countryCodes.put("1-671",   new CRow("1-671",   "GU", "GUM", "Guam"));
        countryCodes.put("1-684",   new CRow("1-684",   "AS", "ASM", "American Samoa"));
        countryCodes.put("1-721",   new CRow("1-721",   "SX", "SXM", "Sint Maarten"));
        countryCodes.put("1-758",   new CRow("1-758",   "LC", "LCA", "Saint Lucia"));
        countryCodes.put("1-767",   new CRow("1-767",   "DM", "DMA", "Dominica"));
        countryCodes.put("1-784",   new CRow("1-784",   "VC", "VCT", "Saint Vincent and the Grenadines"));
        countryCodes.put("1-787",   new CRow("1-787",   "PR", "PRI", "Puerto Rico"));
        countryCodes.put("1-939",   new CRow("1-939",   "PR", "PRI", "Puerto Rico"));
        countryCodes.put("1-809",   new CRow("1-809",   "DO", "DOM", "Dominican Republic"));
        countryCodes.put("1-829",   new CRow("1-829",   "DO", "DOM", "Dominican Republic"));
        countryCodes.put("1-849",   new CRow("1-849",   "DO", "DOM", "Dominican Republic"));
        countryCodes.put("1-868",   new CRow("1-868",   "TT", "TTO", "Trinidad and Tobago"));
        countryCodes.put("1-869",   new CRow("1-869",   "KN", "KNA", "Saint Kitts and Nevis"));
        countryCodes.put("1-876",   new CRow("1-876",   "JM", "JAM", "Jamaica"));
        countryCodes.put("44-1481", new CRow("44-1481", "GG", "GGY", "Guernsey"));
        countryCodes.put("44-1534", new CRow("44-1534", "JE", "JEY", "Jersey"));
        countryCodes.put("44-1624", new CRow("44-1624", "IM", "IMN", "Isle of Man"));

        // Duplicated code countries
        // countryCodes.put("1",       new CRow("1",       "CA", "CAN", "Canada"));
        // countryCodes.put("7",       new CRow("7",       "KZ", "KAZ", "Kazakhstan"));
        // countryCodes.put("47",      new CRow("47",      "SJ", "SJM", "Svalbard and Jan Mayen"));
        // countryCodes.put("61",      new CRow("61",      "CX", "CXR", "Christmas Island"));
        // countryCodes.put("61",      new CRow("61",      "AU", "AUS", "Australia"));
        // countryCodes.put("64",      new CRow("64",      "PN", "PCN", "Pitcairn"));
        // countryCodes.put("212",     new CRow("212",     "EH", "ESH", "Western Sahara"));
        // countryCodes.put("599",     new CRow("599",     "AN", "ANT", "Netherlands Antilles"));

        areaCodes.put("684", new ARow("684", "AS", "ASM", "American Samoa", "", ""));
        areaCodes.put("264", new ARow("264", "AI", "AIA", "Anguilla", "", ""));
        areaCodes.put("268", new ARow("268", "AG", "ATG", "Antigua and Barbuda", "", ""));
        areaCodes.put("242", new ARow("242", "BS", "BHS", "Bahamas", "", ""));
        areaCodes.put("246", new ARow("246", "BB", "BRB", "Barbados", "", ""));
        areaCodes.put("441", new ARow("441", "BM", "BMU", "Bermuda", "", ""));
        areaCodes.put("284", new ARow("284", "VG", "VGB", "British Virgin Islands", "", ""));
        areaCodes.put("403", new ARow("403", "CA", "CAN", "Canada", "AB", "Alberta"));
        areaCodes.put("587", new ARow("587", "CA", "CAN", "Canada", "AB", "Alberta"));
        areaCodes.put("780", new ARow("780", "CA", "CAN", "Canada", "AB", "Alberta"));
        areaCodes.put("825", new ARow("825", "CA", "CAN", "Canada", "AB", "Alberta"));
        areaCodes.put("236", new ARow("236", "CA", "CAN", "Canada", "BC", "British Columbia"));
        areaCodes.put("250", new ARow("250", "CA", "CAN", "Canada", "BC", "British Columbia"));
        areaCodes.put("604", new ARow("604", "CA", "CAN", "Canada", "BC", "British Columbia"));
        areaCodes.put("778", new ARow("778", "CA", "CAN", "Canada", "BC", "British Columbia"));
        areaCodes.put("204", new ARow("204", "CA", "CAN", "Canada", "MB", "Manitoba"));
        areaCodes.put("431", new ARow("431", "CA", "CAN", "Canada", "MB", "Manitoba"));
        areaCodes.put("506", new ARow("506", "CA", "CAN", "Canada", "NB", "New Brunswick"));
        areaCodes.put("709", new ARow("709", "CA", "CAN", "Canada", "NL", "Newfoundland and Labrador"));
        areaCodes.put("867", new ARow("867", "CA", "CAN", "Canada", "NT, NU, YT", "Northwest Territories, Nunavut, Yukon"));
        areaCodes.put("902", new ARow("902", "CA", "CAN", "Canada", "NS, PE", "Nova Scotia, Prince Edward Island"));
        areaCodes.put("782", new ARow("782", "CA", "CAN", "Canada", "NS, PE", "Nova Scotia, Prince Edward Island"));
        areaCodes.put("226", new ARow("226", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("249", new ARow("249", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("289", new ARow("289", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("343", new ARow("343", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("365", new ARow("365", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("416", new ARow("416", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("437", new ARow("437", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("519", new ARow("519", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("613", new ARow("613", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("647", new ARow("647", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("705", new ARow("705", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("807", new ARow("807", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("905", new ARow("905", "CA", "CAN", "Canada", "ON", "Ontario"));
        areaCodes.put("418", new ARow("418", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("438", new ARow("438", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("450", new ARow("450", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("514", new ARow("514", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("579", new ARow("579", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("581", new ARow("581", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("819", new ARow("819", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("873", new ARow("873", "CA", "CAN", "Canada", "QC", "Quebec"));
        areaCodes.put("306", new ARow("306", "CA", "CAN", "Canada", "SK", "Saskatchewan"));
        areaCodes.put("639", new ARow("639", "CA", "CAN", "Canada", "SK", "Saskatchewan"));
        areaCodes.put("345", new ARow("345", "KY", "CYM", "Cayman Islands", "", ""));
        areaCodes.put("767", new ARow("767", "DM", "DMA", "Dominica", "", ""));
        areaCodes.put("809", new ARow("809", "DO", "DOM", "Dominican Republic", "", ""));
        areaCodes.put("829", new ARow("829", "DO", "DOM", "Dominican Republic", "", ""));
        areaCodes.put("849", new ARow("849", "DO", "DOM", "Dominican Republic", "", ""));
        areaCodes.put("473", new ARow("473", "GD", "GRD", "Grenada", "", ""));
        areaCodes.put("671", new ARow("671", "GU", "GUM", "Guam", "", ""));
        areaCodes.put("876", new ARow("876", "JM", "JAM", "Jamaica", "", ""));
        areaCodes.put("664", new ARow("664", "MS", "MSR", "Montserrat", "", ""));
        areaCodes.put("670", new ARow("670", "MP", "MNP", "Northern Mariana Islands", "", ""));
        areaCodes.put("787", new ARow("787", "PR", "PRI", "Puerto Rico", "", ""));
        areaCodes.put("939", new ARow("939", "PR", "PRI", "Puerto Rico", "", ""));
        areaCodes.put("869", new ARow("869", "KN", "KNA", "Saint Kitts and Nevis", "", ""));
        areaCodes.put("758", new ARow("758", "LC", "LCA", "Saint Lucia", "", ""));
        areaCodes.put("784", new ARow("784", "VC", "VCT", "Saint Vincent and the Grenadines", "", ""));
        areaCodes.put("721", new ARow("721", "SX", "SXM", "Sint Maarten", "", ""));
        areaCodes.put("868", new ARow("868", "TT", "TTO", "Trinidad and Tobago", "", ""));
        areaCodes.put("649", new ARow("649", "TC", "TCA", "Turks and Caicos Islands", "", ""));
        areaCodes.put("205", new ARow("205", "US", "USA", "United States", "AL", "Alabama"));
        areaCodes.put("251", new ARow("251", "US", "USA", "United States", "AL", "Alabama"));
        areaCodes.put("256", new ARow("256", "US", "USA", "United States", "AL", "Alabama"));
        areaCodes.put("334", new ARow("334", "US", "USA", "United States", "AL", "Alabama"));
        areaCodes.put("907", new ARow("907", "US", "USA", "United States", "AK", "Alaska"));
        areaCodes.put("480", new ARow("480", "US", "USA", "United States", "AZ", "Arizona"));
        areaCodes.put("520", new ARow("520", "US", "USA", "United States", "AZ", "Arizona"));
        areaCodes.put("602", new ARow("602", "US", "USA", "United States", "AZ", "Arizona"));
        areaCodes.put("623", new ARow("623", "US", "USA", "United States", "AZ", "Arizona"));
        areaCodes.put("928", new ARow("928", "US", "USA", "United States", "AZ", "Arizona"));
        areaCodes.put("479", new ARow("479", "US", "USA", "United States", "AR", "Arkansas"));
        areaCodes.put("501", new ARow("501", "US", "USA", "United States", "AR", "Arkansas"));
        areaCodes.put("870", new ARow("870", "US", "USA", "United States", "AR", "Arkansas"));
        areaCodes.put("209", new ARow("209", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("213", new ARow("213", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("310", new ARow("310", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("323", new ARow("323", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("408", new ARow("408", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("415", new ARow("415", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("510", new ARow("510", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("530", new ARow("530", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("559", new ARow("559", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("562", new ARow("562", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("619", new ARow("619", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("626", new ARow("626", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("650", new ARow("650", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("661", new ARow("661", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("707", new ARow("707", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("714", new ARow("714", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("760", new ARow("760", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("805", new ARow("805", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("818", new ARow("818", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("831", new ARow("831", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("858", new ARow("858", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("909", new ARow("909", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("916", new ARow("916", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("925", new ARow("925", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("949", new ARow("949", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("951", new ARow("951", "US", "USA", "United States", "CA", "California"));
        areaCodes.put("303", new ARow("303", "US", "USA", "United States", "CO", "Colorado"));
        areaCodes.put("719", new ARow("719", "US", "USA", "United States", "CO", "Colorado"));
        areaCodes.put("970", new ARow("970", "US", "USA", "United States", "CO", "Colorado"));
        areaCodes.put("203", new ARow("203", "US", "USA", "United States", "CT", "Connecticut"));
        areaCodes.put("860", new ARow("860", "US", "USA", "United States", "CT", "Connecticut"));
        areaCodes.put("302", new ARow("302", "US", "USA", "United States", "DE", "Delaware"));
        areaCodes.put("202", new ARow("202", "US", "USA", "United States", "DC", "District of Columbia"));
        areaCodes.put("239", new ARow("239", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("305", new ARow("305", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("321", new ARow("321", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("352", new ARow("352", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("386", new ARow("386", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("407", new ARow("407", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("561", new ARow("561", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("727", new ARow("727", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("772", new ARow("772", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("813", new ARow("813", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("850", new ARow("850", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("863", new ARow("863", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("904", new ARow("904", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("941", new ARow("941", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("954", new ARow("954", "US", "USA", "United States", "FL", "Florida"));
        areaCodes.put("229", new ARow("229", "US", "USA", "United States", "GA", "Georgia"));
        areaCodes.put("404", new ARow("404", "US", "USA", "United States", "GA", "Georgia"));
        areaCodes.put("478", new ARow("478", "US", "USA", "United States", "GA", "Georgia"));
        areaCodes.put("706", new ARow("706", "US", "USA", "United States", "GA", "Georgia"));
        areaCodes.put("770", new ARow("770", "US", "USA", "United States", "GA", "Georgia"));
        areaCodes.put("912", new ARow("912", "US", "USA", "United States", "GA", "Georgia"));
        areaCodes.put("808", new ARow("808", "US", "USA", "United States", "HI", "Hawaii"));
        areaCodes.put("208", new ARow("208", "US", "USA", "United States", "ID", "Idaho"));
        areaCodes.put("217", new ARow("217", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("309", new ARow("309", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("312", new ARow("312", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("618", new ARow("618", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("630", new ARow("630", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("708", new ARow("708", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("773", new ARow("773", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("815", new ARow("815", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("847", new ARow("847", "US", "USA", "United States", "IL", "Illinois"));
        areaCodes.put("219", new ARow("219", "US", "USA", "United States", "IN", "Indiana"));
        areaCodes.put("260", new ARow("260", "US", "USA", "United States", "IN", "Indiana"));
        areaCodes.put("317", new ARow("317", "US", "USA", "United States", "IN", "Indiana"));
        areaCodes.put("574", new ARow("574", "US", "USA", "United States", "IN", "Indiana"));
        areaCodes.put("765", new ARow("765", "US", "USA", "United States", "IN", "Indiana"));
        areaCodes.put("812", new ARow("812", "US", "USA", "United States", "IN", "Indiana"));
        areaCodes.put("319", new ARow("319", "US", "USA", "United States", "IA", "Iowa"));
        areaCodes.put("515", new ARow("515", "US", "USA", "United States", "IA", "Iowa"));
        areaCodes.put("563", new ARow("563", "US", "USA", "United States", "IA", "Iowa"));
        areaCodes.put("641", new ARow("641", "US", "USA", "United States", "IA", "Iowa"));
        areaCodes.put("712", new ARow("712", "US", "USA", "United States", "IA", "Iowa"));
        areaCodes.put("316", new ARow("316", "US", "USA", "United States", "KS", "Kansas"));
        areaCodes.put("620", new ARow("620", "US", "USA", "United States", "KS", "Kansas"));
        areaCodes.put("785", new ARow("785", "US", "USA", "United States", "KS", "Kansas"));
        areaCodes.put("913", new ARow("913", "US", "USA", "United States", "KS", "Kansas"));
        areaCodes.put("270", new ARow("270", "US", "USA", "United States", "KY", "Kentucky"));
        areaCodes.put("502", new ARow("502", "US", "USA", "United States", "KY", "Kentucky"));
        areaCodes.put("606", new ARow("606", "US", "USA", "United States", "KY", "Kentucky"));
        areaCodes.put("859", new ARow("859", "US", "USA", "United States", "KY", "Kentucky"));
        areaCodes.put("225", new ARow("225", "US", "USA", "United States", "LA", "Louisiana"));
        areaCodes.put("318", new ARow("318", "US", "USA", "United States", "LA", "Louisiana"));
        areaCodes.put("337", new ARow("337", "US", "USA", "United States", "LA", "Louisiana"));
        areaCodes.put("504", new ARow("504", "US", "USA", "United States", "LA", "Louisiana"));
        areaCodes.put("985", new ARow("985", "US", "USA", "United States", "LA", "Louisiana"));
        areaCodes.put("207", new ARow("207", "US", "USA", "United States", "ME", "Maine"));
        areaCodes.put("301", new ARow("301", "US", "USA", "United States", "MD", "Maryland"));
        areaCodes.put("410", new ARow("410", "US", "USA", "United States", "MD", "Maryland"));
        areaCodes.put("413", new ARow("413", "US", "USA", "United States", "MA", "Massachusetts"));
        areaCodes.put("508", new ARow("508", "US", "USA", "United States", "MA", "Massachusetts"));
        areaCodes.put("617", new ARow("617", "US", "USA", "United States", "MA", "Massachusetts"));
        areaCodes.put("781", new ARow("781", "US", "USA", "United States", "MA", "Massachusetts"));
        areaCodes.put("978", new ARow("978", "US", "USA", "United States", "MA", "Massachusetts"));
        areaCodes.put("231", new ARow("231", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("248", new ARow("248", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("269", new ARow("269", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("313", new ARow("313", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("517", new ARow("517", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("586", new ARow("586", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("616", new ARow("616", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("734", new ARow("734", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("810", new ARow("810", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("906", new ARow("906", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("989", new ARow("989", "US", "USA", "United States", "MI", "Michigan"));
        areaCodes.put("218", new ARow("218", "US", "USA", "United States", "MN", "Minnesota"));
        areaCodes.put("320", new ARow("320", "US", "USA", "United States", "MN", "Minnesota"));
        areaCodes.put("507", new ARow("507", "US", "USA", "United States", "MN", "Minnesota"));
        areaCodes.put("612", new ARow("612", "US", "USA", "United States", "MN", "Minnesota"));
        areaCodes.put("651", new ARow("651", "US", "USA", "United States", "MN", "Minnesota"));
        areaCodes.put("763", new ARow("763", "US", "USA", "United States", "MN", "Minnesota"));
        areaCodes.put("952", new ARow("952", "US", "USA", "United States", "MN", "Minnesota"));
        areaCodes.put("228", new ARow("228", "US", "USA", "United States", "MS", "Mississippi"));
        areaCodes.put("601", new ARow("601", "US", "USA", "United States", "MS", "Mississippi"));
        areaCodes.put("662", new ARow("662", "US", "USA", "United States", "MS", "Mississippi"));
        areaCodes.put("314", new ARow("314", "US", "USA", "United States", "MO", "Missouri"));
        areaCodes.put("417", new ARow("417", "US", "USA", "United States", "MO", "Missouri"));
        areaCodes.put("573", new ARow("573", "US", "USA", "United States", "MO", "Missouri"));
        areaCodes.put("636", new ARow("636", "US", "USA", "United States", "MO", "Missouri"));
        areaCodes.put("660", new ARow("660", "US", "USA", "United States", "MO", "Missouri"));
        areaCodes.put("816", new ARow("816", "US", "USA", "United States", "MO", "Missouri"));
        areaCodes.put("406", new ARow("406", "US", "USA", "United States", "MT", "Montana"));
        areaCodes.put("308", new ARow("308", "US", "USA", "United States", "NE", "Nebraska"));
        areaCodes.put("402", new ARow("402", "US", "USA", "United States", "NE", "Nebraska"));
        areaCodes.put("702", new ARow("702", "US", "USA", "United States", "NV", "Nevada"));
        areaCodes.put("775", new ARow("775", "US", "USA", "United States", "NV", "Nevada"));
        areaCodes.put("603", new ARow("603", "US", "USA", "United States", "NH", "New Hampshire"));
        areaCodes.put("201", new ARow("201", "US", "USA", "United States", "NJ", "New Jersey"));
        areaCodes.put("609", new ARow("609", "US", "USA", "United States", "NJ", "New Jersey"));
        areaCodes.put("732", new ARow("732", "US", "USA", "United States", "NJ", "New Jersey"));
        areaCodes.put("856", new ARow("856", "US", "USA", "United States", "NJ", "New Jersey"));
        areaCodes.put("908", new ARow("908", "US", "USA", "United States", "NJ", "New Jersey"));
        areaCodes.put("973", new ARow("973", "US", "USA", "United States", "NJ", "New Jersey"));
        areaCodes.put("505", new ARow("505", "US", "USA", "United States", "NM", "New Mexico"));
        areaCodes.put("575", new ARow("575", "US", "USA", "United States", "NM", "New Mexico"));
        areaCodes.put("212", new ARow("212", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("315", new ARow("315", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("516", new ARow("516", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("518", new ARow("518", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("585", new ARow("585", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("607", new ARow("607", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("631", new ARow("631", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("716", new ARow("716", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("718", new ARow("718", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("845", new ARow("845", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("914", new ARow("914", "US", "USA", "United States", "NY", "New York"));
        areaCodes.put("252", new ARow("252", "US", "USA", "United States", "NC", "North Carolina"));
        areaCodes.put("336", new ARow("336", "US", "USA", "United States", "NC", "North Carolina"));
        areaCodes.put("704", new ARow("704", "US", "USA", "United States", "NC", "North Carolina"));
        areaCodes.put("828", new ARow("828", "US", "USA", "United States", "NC", "North Carolina"));
        areaCodes.put("910", new ARow("910", "US", "USA", "United States", "NC", "North Carolina"));
        areaCodes.put("919", new ARow("919", "US", "USA", "United States", "NC", "North Carolina"));
        areaCodes.put("701", new ARow("701", "US", "USA", "United States", "ND", "North Dakota"));
        areaCodes.put("216", new ARow("216", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("330", new ARow("330", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("419", new ARow("419", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("440", new ARow("440", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("513", new ARow("513", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("614", new ARow("614", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("740", new ARow("740", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("937", new ARow("937", "US", "USA", "United States", "OH", "Ohio"));
        areaCodes.put("405", new ARow("405", "US", "USA", "United States", "OK", "Oklahoma"));
        areaCodes.put("580", new ARow("580", "US", "USA", "United States", "OK", "Oklahoma"));
        areaCodes.put("918", new ARow("918", "US", "USA", "United States", "OK", "Oklahoma"));
        areaCodes.put("503", new ARow("503", "US", "USA", "United States", "OR", "Oregon"));
        areaCodes.put("541", new ARow("541", "US", "USA", "United States", "OR", "Oregon"));
        areaCodes.put("215", new ARow("215", "US", "USA", "United States", "PA", "Pennsylvania"));
        areaCodes.put("412", new ARow("412", "US", "USA", "United States", "PA", "Pennsylvania"));
        areaCodes.put("570", new ARow("570", "US", "USA", "United States", "PA", "Pennsylvania"));
        areaCodes.put("610", new ARow("610", "US", "USA", "United States", "PA", "Pennsylvania"));
        areaCodes.put("717", new ARow("717", "US", "USA", "United States", "PA", "Pennsylvania"));
        areaCodes.put("724", new ARow("724", "US", "USA", "United States", "PA", "Pennsylvania"));
        areaCodes.put("814", new ARow("814", "US", "USA", "United States", "PA", "Pennsylvania"));
        areaCodes.put("401", new ARow("401", "US", "USA", "United States", "RI", "Rhode Island"));
        areaCodes.put("803", new ARow("803", "US", "USA", "United States", "SC", "South Carolina"));
        areaCodes.put("843", new ARow("843", "US", "USA", "United States", "SC", "South Carolina"));
        areaCodes.put("864", new ARow("864", "US", "USA", "United States", "SC", "South Carolina"));
        areaCodes.put("605", new ARow("605", "US", "USA", "United States", "SD", "South Dakota"));
        areaCodes.put("423", new ARow("423", "US", "USA", "United States", "TN", "Tennessee"));
        areaCodes.put("615", new ARow("615", "US", "USA", "United States", "TN", "Tennessee"));
        areaCodes.put("731", new ARow("731", "US", "USA", "United States", "TN", "Tennessee"));
        areaCodes.put("865", new ARow("865", "US", "USA", "United States", "TN", "Tennessee"));
        areaCodes.put("901", new ARow("901", "US", "USA", "United States", "TN", "Tennessee"));
        areaCodes.put("931", new ARow("931", "US", "USA", "United States", "TN", "Tennessee"));
        areaCodes.put("210", new ARow("210", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("214", new ARow("214", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("254", new ARow("254", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("281", new ARow("281", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("325", new ARow("325", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("361", new ARow("361", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("409", new ARow("409", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("432", new ARow("432", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("512", new ARow("512", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("713", new ARow("713", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("806", new ARow("806", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("817", new ARow("817", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("830", new ARow("830", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("903", new ARow("903", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("915", new ARow("915", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("936", new ARow("936", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("940", new ARow("940", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("956", new ARow("956", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("972", new ARow("972", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("979", new ARow("979", "US", "USA", "United States", "TX", "Texas"));
        areaCodes.put("435", new ARow("435", "US", "USA", "United States", "UT", "Utah"));
        areaCodes.put("801", new ARow("801", "US", "USA", "United States", "UT", "Utah"));
        areaCodes.put("802", new ARow("802", "US", "USA", "United States", "VT", "Vermont"));
        areaCodes.put("276", new ARow("276", "US", "USA", "United States", "VA", "Virginia"));
        areaCodes.put("434", new ARow("434", "US", "USA", "United States", "VA", "Virginia"));
        areaCodes.put("540", new ARow("540", "US", "USA", "United States", "VA", "Virginia"));
        areaCodes.put("703", new ARow("703", "US", "USA", "United States", "VA", "Virginia"));
        areaCodes.put("757", new ARow("757", "US", "USA", "United States", "VA", "Virginia"));
        areaCodes.put("804", new ARow("804", "US", "USA", "United States", "VA", "Virginia"));
        areaCodes.put("206", new ARow("206", "US", "USA", "United States", "WA", "Washington"));
        areaCodes.put("253", new ARow("253", "US", "USA", "United States", "WA", "Washington"));
        areaCodes.put("360", new ARow("360", "US", "USA", "United States", "WA", "Washington"));
        areaCodes.put("425", new ARow("425", "US", "USA", "United States", "WA", "Washington"));
        areaCodes.put("509", new ARow("509", "US", "USA", "United States", "WA", "Washington"));
        areaCodes.put("304", new ARow("304", "US", "USA", "United States", "WV", "West Virginia"));
        areaCodes.put("262", new ARow("262", "US", "USA", "United States", "WI", "Wisconsin"));
        areaCodes.put("414", new ARow("414", "US", "USA", "United States", "WI", "Wisconsin"));
        areaCodes.put("608", new ARow("608", "US", "USA", "United States", "WI", "Wisconsin"));
        areaCodes.put("715", new ARow("715", "US", "USA", "United States", "WI", "Wisconsin"));
        areaCodes.put("920", new ARow("920", "US", "USA", "United States", "WI", "Wisconsin"));
        areaCodes.put("307", new ARow("307", "US", "USA", "United States", "WY", "Wyoming"));
        areaCodes.put("340", new ARow("340", "VI", "VIR", "United States Virgin Islands", "", ""));
    }
}
